version: "1.0"

services:
  frontend:
    build: ./client
    restart: unless-stopped
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  backend:
    build: ./server
    restart: unless-stopped
    ports:
      - 5000:5000
    stdin_open: true
    tty: true